export {Nav} from "./nav";
export {Header} from "./header";
export {Main} from "./main";
export {Footer} from "./footer";
export {About} from "./about";
export {Proyectos} from "./proyectos";
export {Skills} from "./skills";
export {Tecnologias} from "./tecnologias";
export {Error404} from "./error404";
